name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write        # required for version PR and tags
  id-token: write        # for npm provenance
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      # Build everything before publish (libs will actually publish; apps are private)
      - name: Build packages
        run: pnpm -r --filter "./packages/*" run build

      - name: Create Release PR or Publish
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          # Enable npm provenance on publish
          NPM_CONFIG_PROVENANCE: true

